### ISSUE TITLE
List this provider in the Terraform Registry

### ISSUE THREAD

**Issue by mogul** [cloudfoundry-community/terraform-provider-cloudfoundry#270]
As of 0.13, [Terraform will be able to install community provider plugins](https://www.hashicorp.com/blog/automatic-installation-of-third-party-providers-with-terraform-0-13/), but only if they're [listed in the Terraform Registry](https://registry.terraform.io/publish/provider/github/cloudfoundry-community). 

Can you please fill out the form @ArthurHlt?

**Comment by janosbinder** [comment]
I had a look on https://registry.terraform.io/publish/provider/github/cloudfoundry-community/terraform-provider-cf

According to the site, these steps are needed:

The cloudfoundry-community organization has not completed the provider publishing application process.

In order to begin publishing providers to the Terraform Registry:

* Send an email to terraform-registry@hashicorp.com with a description of the Terraform providers you would like to publish.
* Provide us with a GPG Public Key (in ASCII-Armor format) for the keypair you will use to sign the provider releases.
* Once your application is approved, you can use this screen to publish Terraform providers to the Terraform Registry.
For more information, read our documentation on [Publishing Terraform Providers to the Terraform Registry](https://www.terraform.io/docs/registry/providers/publishing.html)

**Comment by mogul** [comment]
(Also tagging @psycofdj.)

**Comment by loafoe** [comment]
@janosbinder @ArthurHlt  I followed the process outlined above for our own provider and was able to publish in less than half a day. The only additional steps that are required is to sign the release with a PGP public key of the project/maintainers. This can be done automatically by goreleaser as well as long as `GITHUB_TOKEN` and `GPG_FINGERPRINT` environment variables are set. The ASCII armored PGP public key should be send as part of the email to  terraform-registry@hashicorp.com 

I added a PR #272 which updates the `.goreleaser.yml` accordingly. 

Happy to help in any way to get this provider listed. It'll make distribution and using the provider 10x simpler 👍

**Comment by loafoe** [comment]
@mogul @janosbinder @ArthurHlt  pending release of the provider to the Terraform registry we've build a small custom [Terraform registry](https://github.com/philips-labs/terraform-registry) which can "host" arbitrary Terraform provider releases. As an example we are now able to provide custom builds of the `dev` branch of this project to our teams:

```terraform
terraform {
  required_providers {
    cloudfoundry = {
      source  = "terraform-registry.us-east.philips-healthsuite.com/philips-forks/cloudfoundry"
      version = "0.12.2-202008131826"
    }
  }
}
```

**Comment by mogul** [comment]
[Terraform 0.13 is now generally available.](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-13/)

**Comment by cah-andrew-fitzgerald** [comment]
One thing to note: Terraform 0.13 makes usage of non-registry providers a bit more difficult: https://www.terraform.io/upgrade-guides/0-13.html#new-filesystem-layout-for-local-copies-of-providers

**Comment by ArthurHlt** [comment]
I'm on it thanks for the information

**Comment by ArthurHlt** [comment]
So I've created new release of the provider with some fixes and this version include our signature. I've sent a mail to add our gpg public key in their referential.

I'm waiting for the answer and right after that I will register it on the website, thanks everyone

**Comment by ArthurHlt** [comment]
I'm pleased to announce that provider is available in the terraform registry https://registry.terraform.io/providers/cloudfoundry-community/cloudfoundry/latest and can be installed by simply adding in your tf file those lines if you are in terrraform >= 0.13:

```
terraform {
  required_providers {
    cloudfoundry = {
      source = "cloudfoundry-community/cloudfoundry"
      version = "0.12.4"
    }
  }
}
```

**Comment by fitzoh** [comment]
Great, thanks @ArthurHlt !

**Comment by mogul** [comment]
Thanks so much for pursuing this!
