### ISSUE TITLE
Provider produced inconsistent result after apply using params_json at service_binding

### ISSUE THREAD

**Issue by DenesCs** [cloudfoundry-community/terraform-provider-cloudfoundry#279]
When I would like to pass the autoscaling json parameters at the binding info I am getting this error:

```
Error: Provider produced inconsistent result after apply

When applying changes to module.applications.cloudfoundry_app.hello-world,
provider "cloudfoundry" produced an unexpected new value for was present, but
now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
The autoscaler is getting configured properly but the state of the cloudfoundry_app is being lost. 

terraform version: 0.12.4
cloudfoundry terraform provider version: 0.12.4

deploy.tf
```
resource "cloudfoundry_app" "hello-world" {
  name       = "hello-world"
  space      = var.cf_space_id
  instances  = 1
  memory     = 128
  disk_quota = 768
  timeout    = 600

  docker_image = "mlf.docker.repositories.sap.ondemand.com/hello-world:latest"
  health_check_type = "none"
  strategy = "blue-green"
  service_binding {
    service_instance = "${var.cf_autoscaling_service_id}"
    params_json = <<JSON
{
    "instance_min_count": 1,
    "instance_max_count": 5,
    "scaling_rules": [
        {
            "metric_type": "memoryused",
            "threshold": 90,
            "operator": ">=",
            "adjustment": "+1"
        },
 {
            "metric_type": "memoryused",
            "threshold": 30,
            "operator": "<",
            "adjustment": "-1"
        }

    ]
}
JSON
  }
  routes {
    route = cloudfoundry_route.hello-world.id
  }
}
```

DEGUB log:
2020-09-03T12:24:46.241Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.12.4: 2020/09/03 12:24:46 [ERR] Error writing fields: service_binding.1619914224.params.instance_min_count: '' expected type 'string', got unconvertible type 'float64'

**Comment by loafoe** [comment]
@CsDenes the error suggests the Autoscaler broker is expecting the `instance_min_count` to be a string instead of an integer/float, did you try changing it? We had a similar report from a user for a different broker and that too turned out to be incompatible JSON input.

**Comment by CsDenes** [comment]
@loafoe thanks for your hint. Yes this actually could help but I need to use int values otherwise the autoscaler service throws error. Also using arrays/ nested json objects are not supported currently.

After a quick debugging I found that the issue appears at the load of the results into the statefile. In this [point](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/master/cloudfoundry/structures_app.go#L82) the json_params is loaded to the params variable which is a [typeMap](https://www.terraform.io/docs/extend/schemas/schema-types.html#typemap).  (every value which is not string is producing error)

[This](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/pull/293) change could solve my problem.

**Comment by ArthurHlt** [comment]
thanks for the PR, i'm closing this issue
