### ISSUE TITLE
Wiki: cloudfoundry_network_policy

### ISSUE THREAD

**Issue by MB175** [cloudfoundry-community/terraform-provider-cloudfoundry#395]
Shouldn't the resource be called "cloudfoundry_network_policy" instead of "cf_network_policy"

https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/wiki/resource_network_policy

**Comment by loafoe** [comment]
@MB175 it should yes, the docs were fixed recently here 5c244db7a63d588e9437a93e313eb747b057199a but no release has been done yet. 

In general, since the provider is now published on Terraform Registry we should probably retire the Wiki and refer to https://registry.terraform.io/providers/cloudfoundry-community/cloudfoundry/latest/docs ?

**Comment by MB175** [comment]
@loafoe Ah great to hear, so its just a matter of releasing it to the TF Docs page.

**Comment by loafoe** [comment]
Should be visible now
